access_token: "{{ .bootdev.access_token }}"
refresh_token: "{{ .bootdev.refresh_token }}"
api_url: https://api.boot.dev
color:
    gray: "8"
    green: "2"
    red: "1"
frontend_url: https://boot.dev
last_refresh: 1772756218
